version: '2'

services:
    rabbitmq:
        image: rabbitmq:3
        restart: always
        ports:
            # - "4369:4369"
            #- "5671:5671"
            - "5672:5672"
            #- "25672:25672"

    # mosquitto:
    #     build: /mosquitto
    #     ports:
    #         - "1883:1883"

    http_gateway:
        build: http_gateway/
        restart: always
        ports:
            - "5000:5000"

    